/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Steganography;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MediumTest {
    @Test void ViewWorks() {
        View classUnderTest = new View();
        assertNotNull(classUnderTest.Test("It works!"));
    }
}
