/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Steganography;

/**
 *
 * @author ultim
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EncodeBitsButtonGroup = new javax.swing.ButtonGroup();
        DecodeBitsButtonGroup = new javax.swing.ButtonGroup();
        EncodeBaseFilePathLabel = new javax.swing.JLabel();
        EncodeBaseFilePathField = new javax.swing.JTextField();
        EncodeInputFilePathLabel = new javax.swing.JLabel();
        EncodeInputFilePathField = new javax.swing.JTextField();
        EncodeBitsNumberLabel = new javax.swing.JLabel();
        EncodeBitsButton_1 = new javax.swing.JRadioButton();
        EncodeBitsButton_2 = new javax.swing.JRadioButton();
        EncodeBitsButton_3 = new javax.swing.JRadioButton();
        EncodeBitsButton_4 = new javax.swing.JRadioButton();
        EncodeBitsButton_5 = new javax.swing.JRadioButton();
        EncodeBitsButton_6 = new javax.swing.JRadioButton();
        EncodeBitsButton_7 = new javax.swing.JRadioButton();
        EncodeBitsButton_8 = new javax.swing.JRadioButton();
        EncodeButton = new javax.swing.JButton();
        EncodeOutputFilePathLabel = new javax.swing.JLabel();
        EncodeOutputFilePathField = new javax.swing.JTextField();
        DecodeBitsButton_4 = new javax.swing.JRadioButton();
        DecodeBitsButton_5 = new javax.swing.JRadioButton();
        DecodeBitsButton_6 = new javax.swing.JRadioButton();
        DecodeBitsButton_7 = new javax.swing.JRadioButton();
        DecodeBitsButton_8 = new javax.swing.JRadioButton();
        DecodeButton = new javax.swing.JButton();
        DecodeOutputFilePathLabel = new javax.swing.JLabel();
        DecodeOutputFilePathField = new javax.swing.JTextField();
        DecodeBaseFilePathLabel = new javax.swing.JLabel();
        DecodeBaseFilePathField = new javax.swing.JTextField();
        DecodeBitsNumberLabel = new javax.swing.JLabel();
        DecodeBitsButton_1 = new javax.swing.JRadioButton();
        DecodeBitsButton_2 = new javax.swing.JRadioButton();
        DecodeBitsButton_3 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EncodeBaseFilePathLabel.setText("Path to Base Medium:");

        EncodeInputFilePathLabel.setText("Path to Input File:");

        EncodeBitsNumberLabel.setText("Number of bits of LSB:");

        EncodeBitsButton_1.setText("1");
        EncodeBitsButton_1.setActionCommand("1");

        EncodeBitsButton_2.setText("2");
        EncodeBitsButton_2.setActionCommand("2");

        EncodeBitsButton_3.setText("3");
        EncodeBitsButton_3.setActionCommand("3");

        EncodeBitsButton_4.setText("4");
        EncodeBitsButton_4.setActionCommand("4");

        EncodeBitsButton_5.setText("5");
        EncodeBitsButton_5.setActionCommand("5");

        EncodeBitsButton_6.setText("6");
        EncodeBitsButton_6.setActionCommand("6");

        EncodeBitsButton_7.setText("7");
        EncodeBitsButton_7.setActionCommand("7");

        EncodeBitsButton_8.setText("8");
        EncodeBitsButton_8.setActionCommand("8");

        EncodeButton.setText("Encode");
        EncodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncodeButtonActionPerformed(evt);
            }
        });

        EncodeOutputFilePathLabel.setText("Path to Output File:");

        DecodeButton.setText("Decode");
        DecodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecodeButtonActionPerformed(evt);
            }
        });

        DecodeOutputFilePathLabel.setText("Path to Output File:");

        DecodeBaseFilePathLabel.setText("Path to Stegano Medium:");

        DecodeBitsNumberLabel.setText("Number of bits of LSB:");

        DecodeBitsButton_1.setText("1");
        DecodeBitsButton_1.setActionCommand("1");

        DecodeBitsButton_2.setText("2");
        DecodeBitsButton_2.setActionCommand("2");

        DecodeBitsButton_3.setText("3");
        DecodeBitsButton_3.setActionCommand("3");

        DecodeBitsButton_4.setText("4");
        DecodeBitsButton_4.setActionCommand("4");

        DecodeBitsButton_5.setText("5");
        DecodeBitsButton_5.setActionCommand("5");

        DecodeBitsButton_6.setText("6");
        DecodeBitsButton_6.setActionCommand("6");

        DecodeBitsButton_7.setText("7");
        DecodeBitsButton_7.setActionCommand("7");

        DecodeBitsButton_8.setText("8");
        DecodeBitsButton_8.setActionCommand("8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DecodeOutputFilePathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DecodeBaseFilePathLabel)))
                    .addComponent(EncodeOutputFilePathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EncodeInputFilePathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EncodeBaseFilePathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EncodeBaseFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EncodeInputFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EncodeOutputFilePathField)
                    .addComponent(DecodeBaseFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DecodeOutputFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(EncodeBitsNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(EncodeBitsButton_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EncodeBitsButton_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EncodeBitsButton_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EncodeBitsButton_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EncodeBitsButton_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EncodeBitsButton_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EncodeBitsButton_7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EncodeBitsButton_8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(DecodeBitsNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(DecodeBitsButton_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DecodeBitsButton_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DecodeBitsButton_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DecodeBitsButton_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DecodeBitsButton_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DecodeBitsButton_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DecodeBitsButton_7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DecodeBitsButton_8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EncodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(DecodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncodeBaseFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EncodeBaseFilePathLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncodeInputFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EncodeInputFilePathLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncodeBitsNumberLabel)
                    .addComponent(EncodeBitsButton_1)
                    .addComponent(EncodeBitsButton_2)
                    .addComponent(EncodeBitsButton_3)
                    .addComponent(EncodeBitsButton_4)
                    .addComponent(EncodeBitsButton_5)
                    .addComponent(EncodeBitsButton_6)
                    .addComponent(EncodeBitsButton_7)
                    .addComponent(EncodeBitsButton_8))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncodeOutputFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EncodeOutputFilePathLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EncodeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DecodeBaseFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DecodeBaseFilePathLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DecodeBitsNumberLabel)
                    .addComponent(DecodeBitsButton_1)
                    .addComponent(DecodeBitsButton_2)
                    .addComponent(DecodeBitsButton_3)
                    .addComponent(DecodeBitsButton_4)
                    .addComponent(DecodeBitsButton_5)
                    .addComponent(DecodeBitsButton_6)
                    .addComponent(DecodeBitsButton_7)
                    .addComponent(DecodeBitsButton_8))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DecodeOutputFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DecodeOutputFilePathLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DecodeButton)
                .addGap(64, 64, 64))
        );

        EncodeBitsButtonGroup.add(EncodeBitsButton_1);
        EncodeBitsButtonGroup.add(EncodeBitsButton_2);
        EncodeBitsButtonGroup.add(EncodeBitsButton_3);
        EncodeBitsButtonGroup.add(EncodeBitsButton_4);
        EncodeBitsButtonGroup.add(EncodeBitsButton_5);
        EncodeBitsButtonGroup.add(EncodeBitsButton_6);
        EncodeBitsButtonGroup.add(EncodeBitsButton_7);
        EncodeBitsButtonGroup.add(EncodeBitsButton_8);

        DecodeBitsButtonGroup.add(DecodeBitsButton_1);
        DecodeBitsButtonGroup.add(DecodeBitsButton_2);
        DecodeBitsButtonGroup.add(DecodeBitsButton_3);
        DecodeBitsButtonGroup.add(DecodeBitsButton_4);
        DecodeBitsButtonGroup.add(DecodeBitsButton_5);
        DecodeBitsButtonGroup.add(DecodeBitsButton_6);
        DecodeBitsButtonGroup.add(DecodeBitsButton_7);
        DecodeBitsButtonGroup.add(DecodeBitsButton_8);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EncodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncodeButtonActionPerformed
        try {
            Medium m = new Medium(EncodeBaseFilePathField.getText(), EncodeInputFilePathField.getText(), EncodeOutputFilePathField.getText());
            m.lsb(Integer.parseInt(EncodeBitsButtonGroup.getSelection().getActionCommand()));
            javax.swing.JOptionPane.showMessageDialog(null, "Done!");
        }
        catch (Exception e) {
            System.out.println(e.getStackTrace());
            javax.swing.JOptionPane.showMessageDialog(null, "Error!");
        }

    }//GEN-LAST:event_EncodeButtonActionPerformed

    private void DecodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecodeButtonActionPerformed
        try {
            Medium m = new Medium(DecodeBaseFilePathField.getText(), DecodeOutputFilePathField.getText());
            m.read(Integer.parseInt(DecodeBitsButtonGroup.getSelection().getActionCommand()));
            javax.swing.JOptionPane.showMessageDialog(null, "Done!");
        }
        catch (Exception e) {
            System.out.println(e.getStackTrace());
            javax.swing.JOptionPane.showMessageDialog(null, "Error!");
        }
    }//GEN-LAST:event_DecodeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    public int Test(String message) {
        javax.swing.JOptionPane.showMessageDialog(null, message);
        return 1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DecodeBaseFilePathField;
    private javax.swing.JLabel DecodeBaseFilePathLabel;
    private javax.swing.JRadioButton DecodeBitsButton_1;
    private javax.swing.JRadioButton DecodeBitsButton_2;
    private javax.swing.JRadioButton DecodeBitsButton_3;
    private javax.swing.JRadioButton DecodeBitsButton_4;
    private javax.swing.JRadioButton DecodeBitsButton_5;
    private javax.swing.JRadioButton DecodeBitsButton_6;
    private javax.swing.JRadioButton DecodeBitsButton_7;
    private javax.swing.JRadioButton DecodeBitsButton_8;
    private javax.swing.JLabel DecodeBitsNumberLabel;
    private javax.swing.JButton DecodeButton;
    private javax.swing.JTextField DecodeOutputFilePathField;
    private javax.swing.JLabel DecodeOutputFilePathLabel;
    private javax.swing.JTextField EncodeBaseFilePathField;
    private javax.swing.JLabel EncodeBaseFilePathLabel;
    private javax.swing.JRadioButton EncodeBitsButton_1;
    private javax.swing.JRadioButton EncodeBitsButton_2;
    private javax.swing.JRadioButton EncodeBitsButton_3;
    private javax.swing.JRadioButton EncodeBitsButton_4;
    private javax.swing.JRadioButton EncodeBitsButton_5;
    private javax.swing.JRadioButton EncodeBitsButton_6;
    private javax.swing.JRadioButton EncodeBitsButton_7;
    private javax.swing.JRadioButton EncodeBitsButton_8;
    private javax.swing.JLabel EncodeBitsNumberLabel;
    private javax.swing.JButton EncodeButton;
    private javax.swing.JTextField EncodeInputFilePathField;
    private javax.swing.JLabel EncodeInputFilePathLabel;
    private javax.swing.JTextField EncodeOutputFilePathField;
    private javax.swing.JLabel EncodeOutputFilePathLabel;
    private javax.swing.ButtonGroup EncodeBitsButtonGroup;
    private javax.swing.ButtonGroup DecodeBitsButtonGroup;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
